### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by mablae**

### CODE REVIEW

**Comment by oscarotero** [comment]
Why did you close this?

**Comment by mablae** [comment]
I wasn't sure about it.  Sorry for the confusion.
But for my understanding the robo depedency should be mentioned in composer? 

I am currently working on an implementation as a Symfony Bundle using the Symfony2 Console to get rid of robo completly. Also I made some changes to twig extractor, to be able to load the Symfony2 `\Twig_Environment`. 

I am still working on it, to make it extendable. I am using legacy PO files inside twig using a `\Twig_Simplefunction` named `--()` . That part already works, but I also want it to parse the Twig_I18n Extensions format  (Even if I dont use it atm)

Would you accept PRs on the Twig.php to make the \Twig_Environment injectable from outside? 

Very nice lib, thank you. I was doing the extracting with original (c-code unix) xgettext util util I noticed it wasn't able to parse twig files. I can report that po mode also seems to work with pot files. 

Maybe there is room to extend your lib with explicit pot file support, too? 
I hardcoded that into the switch statement. Not that good. 

Are you interesting in mentioning my Symfony2 integration in your Readme, when it is ready? 

Maybe the iterator stuff could be its own Class not bounded to robo, too. This way, we could reuse it in both CLI runners, Syfmony2 and Robo. Make it part of the main gettext lib? 

Sorry to much words... We also can discuss on twitter or IRC, if you'd like, too.

Cheers :beer: :smoking: :leaves:

**Comment by oscarotero** [comment]
>  But for my understanding the robo depedency should be mentioned in composer? 

Yes, maybe you're right. This is a robo tasks, so robo is required to work.

> Would you accept PRs on the Twig.php to make the \Twig_Environment injectable from outside?

Yes, PR are welcome but I'm not familiarized with twig. The current twig implementation was created by @assembledadam. Note that the it uses the Twig i18n extension.

> Maybe there is room to extend your lib with explicit pot file support, too?

Good idea.

> Are you interesting in mentioning my Symfony2 integration in your Readme, when it is ready? 

Of course.

> Maybe the iterator stuff could be its own Class not bounded to robo, too. This way, we could reuse it in both CLI runners, Syfmony2 and Robo. Make it part of the main gettext lib?

I think the iterator is out of the scope of the main gettext lib.

**Comment by mablae** [comment]
> I think the iterator is out of the scope of the main gettext lib.

@oscarotero Okay, I'll bundle up the Symfony stuff I got working and give you a ping then! 

The Twig Extractor in your current master just somehow wrangles the twig template into the PhpCode Parser. Here is how I did it: 

``` php
        if ($node instanceof \Twig_Node_Expression_Function) { //Process nodes that are function expressions
            if ($node->getAttribute('name') == '__') { //Check the function name for __()
                foreach ($node->getNode('arguments') as $argument) { //Grab the argument
                    $key = eval('return '.self::$twig->compile($argument).';');
                    $translations->insert('', $key)->addReference($fileReference, $node->getLine());
                    break; //I only needed the first argument in my implementation
                }
            }
        }
```

**Comment by mablae** [comment]
https://github.com/mablae/gettext-bundle

**Comment by oscarotero** [comment]
The extractor included in master compile the twig source, returning a string with the php code and them use the phpCode extractor to search the functions gettext, ngettext and __ (used by i18n extension).
The problem with i18n extension is it uses the native gettext functions and there's no way to configure other functions (There's an issue for that https://github.com/oscarotero/Gettext/issues/82)

What are you doing is creating your custom gettext functions, right? I'm fine with this, but maybe this approach should create a different extractor. I mean there's should be a TwigI18n extractor and a TwigFunction extractor.

Other things I see in your implementation:
- You're using eval() to compile the argument. I'd avoid this.
- Only `__` function is searched. There are other functions like `n__`, `p__`, etc that should be included.

**Comment by mablae** [comment]
My implementation searches for the legacy function `__()`  which is mapped by my own twig Extension to the php equivalent. I will extend that, so any native gettext function can be mapped  and extracted.

On the other side the SymfonyTwig searches for `{% trans %}Translation{% endtrans %}` Blocks which is the default symfony way of translations. (Introduced by symfony/twig-brigde)

The third one would be support for the TwigI18nExtension the master already has. I dont know yet how much the behaivor differs from symfony/twig-bridge. At best both work similar.

Eval is evil, right. Any idea to avoid it while maintaining the current behavior just compiling the node? 

Thanks for your feedback so far.

**Comment by oscarotero** [comment]
First, I think this conversation should be made in the gettext repository, so please, can you create a issue with this?
Second, I didn't know twig-bridge (as said, I'm not a twig guy) but seems like a way to create custom functions in the templates, right? So you're compiling these functions to get the arguments.
I'm not sure what is eval for, but in phpCode extractor there's a method to transform the arguments without use eval (here: https://github.com/oscarotero/Gettext/blob/master/src/Extractors/PhpCode.php#L57). 

Thank you.

**Pull request closed without merging**
